In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('general_model_full.csv')
data

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
0,2,1,0,820504,1011122,19,115937.7118,30.878789,二層,十三層,...,1,1,3.216651,2.360415,6.347960,0.421408,0.259130,0.311712,0.082275,101-11
1,3,1,1,850923,1020204,17,234202.7068,59.350563,二十四層,三十層,...,1,1,8.482000,1.320465,0.893130,0.957701,0.794212,0.069713,0.854684,102-02
2,6,1,0,700820,1031209,33,103878.1534,24.066766,二層,二層,...,1,0,2.242399,3.157690,7.202395,1.384427,1.237124,1.259014,0.942919,103-12
3,7,1,0,690325,1040913,35,110000.4950,73.568000,全,二層,...,1,0,2.096059,3.258152,7.277277,1.657483,1.468159,1.413863,1.211620,104-09
4,8,1,0,690325,1090923,40,99940.9456,80.047632,全,二層,...,1,0,2.094389,3.259394,7.277268,1.665824,1.474884,1.416363,1.219951,109-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233663,367014,28,1,870210,1040729,17,74909.4280,76.092230,全,四層,...,1,0,4.398002,2.514017,8.333632,1.433443,0.262413,0.133083,0.240132,104-07
233664,367015,28,1,870210,1100329,23,209769.5390,69.123790,二層，三層，四層,四層,...,1,0,4.403582,2.505987,8.340752,1.441099,0.271113,0.130807,0.232397,110-03
233665,367016,28,1,870210,1090608,22,210586.0716,68.285930,二層，三層，四層,四層,...,1,0,4.389162,2.499071,8.329609,1.431733,0.273903,0.113285,0.224624,109-06
233666,367017,28,0,780615,1020804,24,114698.0368,36.618050,五層,五層,...,1,0,3.198488,2.308803,7.106325,0.309806,0.361038,0.450016,0.522547,102-08
233667,367018,28,0,860625,1020618,16,106949.2416,18.700540,五層,七層,...,1,0,4.752600,2.260364,8.279950,1.700334,0.524938,0.120486,0.493112,102-06

In [3]:
data.columns

Index(['id', 'section', 'parking_space', 'construction_time', 'trade_time',
       'age', 'unit_price_ping', 'area', 'trasaction_floor', 'total_floor',
       'floor', 'type', 'room', 'lr', 'bath', 'partition', 'mgmt', 'min_inci',
       'min_hos', 'min_mrt', 'min_mart', 'min_gas', 'min_school', 'min_park',
       'yearMonth'],
      dtype='object')

In [4]:
data.yearMonth.value_counts()

102-07    4733
102-10    4438
102-11    4394
102-05    4165
102-03    4108
          ...
102-00       1
99-11        1
99-08        1
99-03        1
90-72        1
Name: yearMonth, Length: 150, dtype: int64

In [5]:
# 長度7也是有格式錯誤的
data[data.yearMonth == '102-00']

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
13600,16593,3,0,1011031,1020000,1,322662.609,40.289944,八層,十層,...,1,1,8.635804,1.455116,1.080314,0.525848,0.671512,0.726854,0.139126,102-00

# Deal with construction_time & trade_time which length is shorter than 6

In [6]:
# 先把construction_time長度小於6的都篩掉(轉格式or剔除)
j = 0
for i in range(len(data)) :   
    if len(data.construction_time[i].astype(str)) < 6 :
        if len(data.construction_time[i].astype(str)) == 4 :
            data.construction_time[i] = data.construction_time[i].astype(str)+'00'
            print(data.construction_time[i])
        elif data.construction_time[i].astype(str) == '90909' :
            data.construction_time[i] = '900909'
            print(data.construction_time[i])
        else : 
            data.construction_time[i] = '1100100'
            print(data.construction_time[i])
        j += 1
        
    else :
        continue
print(j)

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2913521510.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.construction_time[i] = data.construction_time[i].astype(str)+'00'

650400
660400
660400
660400
570500
570500
570500
660400
660800
660800
650800
650800
660100
540100

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2913521510.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.construction_time[i] = '900909'

900909

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2913521510.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.construction_time[i] = '1100100'

1100100
16

In [7]:
# 確認construction_time有無少於長度6的日期
j = 0
for i in range(len(data)) :   
    if len(data.construction_time[i].astype(str)) < 6 :
        j += 1
        print(data.construction_time[i])
        
    else :
        continue
print(j)

0

In [8]:
# 確認trade_time有無小於長度6的日期
j = 0
for i in range(len(data)) :   
    if len(data.trade_time[i].astype(str)) < 6 :
        j += 1
        print(data.trade_time[i])
        
    else :
        continue
print(j)

90723
1

In [9]:
data[data.trade_time == 90723]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
194644,293605,24,1,1021018,90723,-93,559407.476,60.02807,十三層,二十八層,...,1,1,5.259445,0.898567,0.277564,0.16025,0.195572,0.407757,0.184555,90-72

In [10]:
# 刪除trade_time長度5單一筆資料
data = data.drop(index = {194644})

In [11]:
data = data.reset_index(drop = True) # 不設drop = True的話會把index也加進column

In [12]:
# 再次確認trade_time日期
j = 0
for i in range(len(data)) :   
    if len(data.trade_time[i].astype(str)) < 6 :
        j += 1
        print(data.trade_time[i])
        
    else :
        continue
print(j)

0

In [13]:
data.shape

(233667, 25)

# trade_time & construction_time only has length 6、7

#　Deal with trade_time

In [ ]:
# xxx_0x_0x = r'([0-9]{3}0[1-9]0[1-9])'
# xxx_0x_102x = r"([0-9]{3}0[1-9][1-2][0-9])"
# xxx_0x_3x = r"([0-9]{3}0[1-9]3[0-1])"
# xxx_1x_0x = r"([0-9]{3}1[0-2]0[1-9])"
# xxx_1x_102x = r'([0-9]{3}1[0-2][1-2][0-9])'
# xxx_1x_3x = r'([0-9]{3}1[0-2]3[0-1])'

In [14]:
# 先找出trade_time中不符合長度7 or 不符合條件格式的日期
data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/1783253136.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
2232,2525,1,1,1021111,981031,-4,313006.3672,34.951523,十層,二十三層,...,1,1,8.245495,1.521758,1.225684,1.349076,0.114277,0.707744,1.333000,98-10
2233,2526,1,1,1021111,981115,-4,305161.7038,33.687210,十層,二十三層,...,1,1,8.249135,1.518393,1.222813,1.346343,0.114473,0.707838,1.333674,98-11
2237,2530,1,1,1021111,990610,-3,282821.1074,66.367340,十五層,二十三層,...,1,1,8.250778,1.514524,1.216698,1.339760,0.124824,0.697410,1.343794,99-06
2238,2531,1,1,1021111,990510,-3,323617.9852,33.867244,十五層,二十三層,...,1,1,8.245495,1.521758,1.225684,1.349076,0.114277,0.707744,1.333000,99-05
2239,2532,1,1,1021111,990417,-3,318074.1586,32.099577,十五層,二十三層,...,1,1,8.249135,1.518393,1.222813,1.346343,0.114473,0.707838,1.333674,99-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179458,273144,24,1,1010130,990912,-2,556402.5038,88.335730,三層,二十層,...,1,1,4.789390,1.055848,0.246552,0.610172,0.114069,0.282471,0.086236,99-09
210505,324846,20,0,640906,991220,35,101405.4150,19.722900,全,三層,...,1,0,2.976327,0.295437,1.173682,0.307562,0.672182,0.321232,0.061165,99-12
231395,360475,28,0,1010214,991220,-2,159501.5442,93.541840,全,五層,...,1,1,2.478946,2.192669,6.388612,0.637798,0.376001,0.442563,0.186857,99-12
231396,360476,28,0,1010214,991203,-2,151438.6980,91.786730,全,五層,...,1,1,2.481278,2.188354,6.389198,0.634639,0.375079,0.438077,0.186027,99-12
231401,360481,28,0,1010214,991208,-2,150149.4360,83.783580,全,五層,...,1,1,2.467351,2.198179,6.379222,0.649810,0.386030,0.452601,0.180615,99-12

In [15]:
not_match = data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/3591601976.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match = data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

In [16]:
# 重新編碼才能用[]取值
not_match = not_match.reset_index(drop = True)

In [17]:
# trade_time中長度7但不符合條件的日期
for i in range(len(not_match)) :
    if len(not_match.trade_time[i].astype(str)) == 7:
        print(not_match.trade_time[i])
    else :
        continue

1020000
1040000
1040000

In [18]:
# 將trade_time中長度7但不符條件的日期刪除
# data.trade_time.isin([1020000, 1040000]) -> Series.isin(list)
data = data[data.trade_time != 1020000]

In [19]:
data = data[data.trade_time != 1040000]

In [20]:
data

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
0,2,1,0,820504,1011122,19,115937.7118,30.878789,二層,十三層,...,1,1,3.216651,2.360415,6.347960,0.421408,0.259130,0.311712,0.082275,101-11
1,3,1,1,850923,1020204,17,234202.7068,59.350563,二十四層,三十層,...,1,1,8.482000,1.320465,0.893130,0.957701,0.794212,0.069713,0.854684,102-02
2,6,1,0,700820,1031209,33,103878.1534,24.066766,二層,二層,...,1,0,2.242399,3.157690,7.202395,1.384427,1.237124,1.259014,0.942919,103-12
3,7,1,0,690325,1040913,35,110000.4950,73.568000,全,二層,...,1,0,2.096059,3.258152,7.277277,1.657483,1.468159,1.413863,1.211620,104-09
4,8,1,0,690325,1090923,40,99940.9456,80.047632,全,二層,...,1,0,2.094389,3.259394,7.277268,1.665824,1.474884,1.416363,1.219951,109-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233662,367014,28,1,870210,1040729,17,74909.4280,76.092230,全,四層,...,1,0,4.398002,2.514017,8.333632,1.433443,0.262413,0.133083,0.240132,104-07
233663,367015,28,1,870210,1100329,23,209769.5390,69.123790,二層，三層，四層,四層,...,1,0,4.403582,2.505987,8.340752,1.441099,0.271113,0.130807,0.232397,110-03
233664,367016,28,1,870210,1090608,22,210586.0716,68.285930,二層，三層，四層,四層,...,1,0,4.389162,2.499071,8.329609,1.431733,0.273903,0.113285,0.224624,109-06
233665,367017,28,0,780615,1020804,24,114698.0368,36.618050,五層,五層,...,1,0,3.198488,2.308803,7.106325,0.309806,0.361038,0.450016,0.522547,102-08
233666,367018,28,0,860625,1020618,16,106949.2416,18.700540,五層,七層,...,1,0,4.752600,2.260364,8.279950,1.700334,0.524938,0.120486,0.493112,102-06

In [21]:
# 再套一次，這次內容就會是不符長度7的日期
not_match = data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2927718375.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match = data[~data.trade_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

In [22]:
# 找出剩餘日期(長度6)不符合格式的日期
not_match[not_match.trade_time.astype(str).str.contains(r'([0-9]{2}0[1-9]0[1-9])|([0-9]{2}0[1-9][1-2][0-9])|([0-9]{2}0[1-9]3[0-1])|([0-9]{2}1[0-2]0[1-9])|([0-9]{2}1[0-2][1-2][0-9])|([0-9]{2}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2643630143.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match[not_match.trade_time.astype(str).str.contains(r'([0-9]{2}0[1-9]0[1-9])|([0-9]{2}0[1-9][1-2][0-9])|([0-9]{2}0[1-9]3[0-1])|([0-9]{2}1[0-2]0[1-9])|([0-9]{2}1[0-2][1-2][0-9])|([0-9]{2}1[0-2]3[0-1])')]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
2232,2525,1,1,1021111,981031,-4,313006.3672,34.951523,十層,二十三層,...,1,1,8.245495,1.521758,1.225684,1.349076,0.114277,0.707744,1.333000,98-10
2233,2526,1,1,1021111,981115,-4,305161.7038,33.687210,十層,二十三層,...,1,1,8.249135,1.518393,1.222813,1.346343,0.114473,0.707838,1.333674,98-11
2237,2530,1,1,1021111,990610,-3,282821.1074,66.367340,十五層,二十三層,...,1,1,8.250778,1.514524,1.216698,1.339760,0.124824,0.697410,1.343794,99-06
2238,2531,1,1,1021111,990510,-3,323617.9852,33.867244,十五層,二十三層,...,1,1,8.245495,1.521758,1.225684,1.349076,0.114277,0.707744,1.333000,99-05
2239,2532,1,1,1021111,990417,-3,318074.1586,32.099577,十五層,二十三層,...,1,1,8.249135,1.518393,1.222813,1.346343,0.114473,0.707838,1.333674,99-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179458,273144,24,1,1010130,990912,-2,556402.5038,88.335730,三層,二十層,...,1,1,4.789390,1.055848,0.246552,0.610172,0.114069,0.282471,0.086236,99-09
210505,324846,20,0,640906,991220,35,101405.4150,19.722900,全,三層,...,1,0,2.976327,0.295437,1.173682,0.307562,0.672182,0.321232,0.061165,99-12
231395,360475,28,0,1010214,991220,-2,159501.5442,93.541840,全,五層,...,1,1,2.478946,2.192669,6.388612,0.637798,0.376001,0.442563,0.186857,99-12
231396,360476,28,0,1010214,991203,-2,151438.6980,91.786730,全,五層,...,1,1,2.481278,2.188354,6.389198,0.634639,0.375079,0.438077,0.186027,99-12
231401,360481,28,0,1010214,991208,-2,150149.4360,83.783580,全,五層,...,1,1,2.467351,2.198179,6.379222,0.649810,0.386030,0.452601,0.180615,99-12

# Deal with construction_time

In [23]:
# 先找出construntion_time中不符合長度7 or 不符合條件格式的日期
data[~data.construction_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/4006146210.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  data[~data.construction_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
0,2,1,0,820504,1011122,19,115937.7118,30.878789,二層,十三層,...,1,1,3.216651,2.360415,6.347960,0.421408,0.259130,0.311712,0.082275,101-11
1,3,1,1,850923,1020204,17,234202.7068,59.350563,二十四層,三十層,...,1,1,8.482000,1.320465,0.893130,0.957701,0.794212,0.069713,0.854684,102-02
2,6,1,0,700820,1031209,33,103878.1534,24.066766,二層,二層,...,1,0,2.242399,3.157690,7.202395,1.384427,1.237124,1.259014,0.942919,103-12
3,7,1,0,690325,1040913,35,110000.4950,73.568000,全,二層,...,1,0,2.096059,3.258152,7.277277,1.657483,1.468159,1.413863,1.211620,104-09
4,8,1,0,690325,1090923,40,99940.9456,80.047632,全,二層,...,1,0,2.094389,3.259394,7.277268,1.665824,1.474884,1.416363,1.219951,109-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233662,367014,28,1,870210,1040729,17,74909.4280,76.092230,全,四層,...,1,0,4.398002,2.514017,8.333632,1.433443,0.262413,0.133083,0.240132,104-07
233663,367015,28,1,870210,1100329,23,209769.5390,69.123790,二層，三層，四層,四層,...,1,0,4.403582,2.505987,8.340752,1.441099,0.271113,0.130807,0.232397,110-03
233664,367016,28,1,870210,1090608,22,210586.0716,68.285930,二層，三層，四層,四層,...,1,0,4.389162,2.499071,8.329609,1.431733,0.273903,0.113285,0.224624,109-06
233665,367017,28,0,780615,1020804,24,114698.0368,36.618050,五層,五層,...,1,0,3.198488,2.308803,7.106325,0.309806,0.361038,0.450016,0.522547,102-08
233666,367018,28,0,860625,1020618,16,106949.2416,18.700540,五層,七層,...,1,0,4.752600,2.260364,8.279950,1.700334,0.524938,0.120486,0.493112,102-06

In [24]:
not_match1 = data[~data.construction_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/756515756.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match1 = data[~data.construction_time.astype(str).str.contains(r'([0-9]{3}0[1-9]0[1-9])|([0-9]{3}0[1-9][1-2][0-9])|([0-9]{3}0[1-9]3[0-1])|([0-9]{3}1[0-2]0[1-9])|([0-9]{3}1[0-2][1-2][0-9])|([0-9]{3}1[0-2]3[0-1])')]

In [25]:
# 重新編碼才能用[]取值
not_match1 = not_match1.reset_index(drop = True)

In [26]:
# construction_time中長度7但不符合條件的日期
for i in range(len(not_match1)) :
    if len(not_match1.construction_time[i].astype(str)) == 7:
        print(not_match1.construction_time[i])
    else :
        continue

1100100

In [27]:
# 將construction_time中長度7但不符條件的日期保留

In [28]:
data

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
0,2,1,0,820504,1011122,19,115937.7118,30.878789,二層,十三層,...,1,1,3.216651,2.360415,6.347960,0.421408,0.259130,0.311712,0.082275,101-11
1,3,1,1,850923,1020204,17,234202.7068,59.350563,二十四層,三十層,...,1,1,8.482000,1.320465,0.893130,0.957701,0.794212,0.069713,0.854684,102-02
2,6,1,0,700820,1031209,33,103878.1534,24.066766,二層,二層,...,1,0,2.242399,3.157690,7.202395,1.384427,1.237124,1.259014,0.942919,103-12
3,7,1,0,690325,1040913,35,110000.4950,73.568000,全,二層,...,1,0,2.096059,3.258152,7.277277,1.657483,1.468159,1.413863,1.211620,104-09
4,8,1,0,690325,1090923,40,99940.9456,80.047632,全,二層,...,1,0,2.094389,3.259394,7.277268,1.665824,1.474884,1.416363,1.219951,109-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233662,367014,28,1,870210,1040729,17,74909.4280,76.092230,全,四層,...,1,0,4.398002,2.514017,8.333632,1.433443,0.262413,0.133083,0.240132,104-07
233663,367015,28,1,870210,1100329,23,209769.5390,69.123790,二層，三層，四層,四層,...,1,0,4.403582,2.505987,8.340752,1.441099,0.271113,0.130807,0.232397,110-03
233664,367016,28,1,870210,1090608,22,210586.0716,68.285930,二層，三層，四層,四層,...,1,0,4.389162,2.499071,8.329609,1.431733,0.273903,0.113285,0.224624,109-06
233665,367017,28,0,780615,1020804,24,114698.0368,36.618050,五層,五層,...,1,0,3.198488,2.308803,7.106325,0.309806,0.361038,0.450016,0.522547,102-08
233666,367018,28,0,860625,1020618,16,106949.2416,18.700540,五層,七層,...,1,0,4.752600,2.260364,8.279950,1.700334,0.524938,0.120486,0.493112,102-06

In [29]:
# 找出日期(長度6&7)中不符合格式的日期，上面沒有將長度7的篩掉所以這裡仍有
not_match1[~not_match1.construction_time.astype(str).str.contains(r'([0-9]{2}0[1-9]0[1-9])|([0-9]{2}0[1-9][1-2][0-9])|([0-9]{2}0[1-9]3[0-1])|([0-9]{2}1[0-2]0[1-9])|([0-9]{2}1[0-2][1-2][0-9])|([0-9]{2}1[0-2]3[0-1])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/2029968317.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match1[~not_match1.construction_time.astype(str).str.contains(r'([0-9]{2}0[1-9]0[1-9])|([0-9]{2}0[1-9][1-2][0-9])|([0-9]{2}0[1-9]3[0-1])|([0-9]{2}1[0-2]0[1-9])|([0-9]{2}1[0-2][1-2][0-9])|([0-9]{2}1[0-2]3[0-1])')]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
2090,3744,1,0,700100,1090527,39,3.286097e+05,69.992153,全,二層,...,1,1,8.011624,1.957085,1.706434,1.858026,0.504761,1.316579,0.716138,109-05
7350,10538,3,0,611000,1090629,48,3.565074e+05,15.427520,二層,四層,...,1,0,6.740014,0.473665,0.548578,0.308227,0.281768,0.449183,0.205146,109-06
8873,13062,3,0,650400,1061117,106,2.700508e+05,21.477537,三層，陽台,四層,...,1,0,5.991975,0.654184,0.448978,0.288690,0.540254,0.305994,0.230446,106-11
9139,13797,3,0,660400,1040814,104,2.668541e+05,25.107466,三層，陽台,四層,...,1,0,6.423079,0.471686,0.351446,0.324888,0.236027,0.414223,0.337576,104-08
9140,13798,3,0,660400,1051025,105,3.026989e+05,25.107573,三層，陽台,四層,...,1,0,6.423079,0.471686,0.351446,0.324888,0.236027,0.414223,0.337576,105-10
9141,13799,3,0,660400,1040119,104,3.663355e+05,14.822544,四層,四層,...,1,0,6.423079,0.471686,0.351446,0.324888,0.236027,0.414223,0.337576,104-01
10374,16229,3,0,570500,1040512,104,3.718298e+05,40.341222,全,三層,...,1,0,8.280465,1.500156,0.425542,0.113229,0.085041,0.556027,0.190839,104-05
10375,16230,3,0,570500,1040512,104,3.443784e+05,43.556934,全,三層,...,1,0,8.278081,1.496444,0.421925,0.109140,0.086515,0.552364,0.192886,104-05
10376,16232,3,0,570500,1020121,102,5.050866e+05,87.114171,全,三層,...,1,0,8.270434,1.487598,0.411700,0.098308,0.089534,0.542052,0.200007,102-01
14521,22384,3,0,610300,1090817,48,6.000258e+05,44.164963,一層，騎樓,四層,...,1,0,7.455753,1.006602,0.613375,0.420553,0.382593,0.652252,0.107774,109-08
14522,22385,3,0,610300,1090817,48,2.490656e+05,44.165273,三層,四層,...,1,0,7.455753,1.006602,0.613375,0.420553,0.382593,0.652252,0.107774,109-08
14802,22806,3,0,660400,1090914,109,1.859512e+05,24.200000,四層，陽台,四層,...,1,0,5.415022,1.041555,0.871959,0.416198,0.826309,0.344843,0.441860,109-09
16601,26492,3,0,660800,1070508,107,6.164854e+05,22.385058,一層,四層,...,1,0,5.609148,0.680296,0.419607,0.161170,0.448569,0.135079,0.081559,107-05
16602,26493,3,0,660800,1031221,103,3.343784e+05,26.317611,四層，陽台,四層,...,1,0,5.615199,0.674195,0.431060,0.155823,0.441688,0.129457,0.071109,103-12
17929,28792,3,0,650800,1090801,109,3.180576e+05,19.965025,二層，陽台,四層,...,1,0,5.520086,0.842748,0.694571,0.190028,0.615762,0.213753,0.237889,109-08
17930,28793,3,0,650800,1091102,109,3.456049e+05,19.965087,二層，陽台,四層,...,1,0,5.520086,0.842748,0.694571,0.190028,0.615762,0.213753,0.237889,109-11
18720,30952,3,0,660100,1071231,107,3.014096e+05,30.855159,四層，陽台,四層,...,1,0,5.615880,0.835382,0.659623,0.339486,0.629817,0.132903,0.400221,107-12
46850,81929,8,0,580600,1090529,51,1.788868e+05,25.043890,三層,四層,...,1,0,3.389272,0.676346,0.344850,0.546714,1.140475,0.124103,0.316970,109-05
55770,95581,8,0,531200,1091015,56,1.307821e+06,22.990000,全,二層,...,1,0,4.784063,0.129455,0.085294,0.133539,0.092720,0.145775,0.233569,109-10
55771,95582,8,0,531200,1091015,56,1.323008e+06,24.200020,全,二層,...,1,0,4.790602,0.119125,0.096651,0.144738,0.084061,0.151794,0.227924,109-10
55772,95583,8,0,531200,1091015,56,1.322611e+06,22.989980,全,二層,...,1,0,4.788210,0.122264,0.092836,0.140968,0.086546,0.149485,0.229983,109-10
64197,115256,9,0,410000,1090723,68,7.809986e+05,69.142560,一層，二層，三層，騎樓,四層,...,1,0,5.260818,0.508689,0.384149,0.319658,1.286247,0.798578,0.083950,109-07
86915,149528,7,0,540100,1070922,107,7.313719e+05,43.069940,全,二層,...,1,0,1.820963,1.376397,0.889096,0.079362,0.152035,0.315954,0.146067,107-09
151007,294343,20,0,1100100,1060103,105,6.591831e+05,15.170360,全,一層,...,1,0,3.002168,0.358144,0.875458,0.535644,0.842623,0.253405,0.202983,106-01
164457,320385,20,0,571200,1090521,52,3.176477e+05,22.037090,二層，陽台,三層,...,1,0,3.676566,0.198632,1.353638,0.311343,0.434226,0.373812,0.314179,109-05
164759,320765,20,0,570100,1100329,53,6.354210e+05,24.865510,全,二層,...,1,0,4.199841,0.312593,1.308067,0.412511,0.789022,0.095216,0.258575,110-03
185321,360554,28,0,700200,1091014,39,6.921023e+04,57.795190,全,二層,...,1,0,1.930117,2.044785,5.697831,1.231612,1.070609,0.879246,0.518490,109-10

In [30]:
# 我們只要篩到月份就好，所以日期是00的可留，但月份00的要刪
not_match1[~not_match1.construction_time.astype(str).str.contains(r'([0-9]{2}0[1-9])|([0-9]{2}0[1-9])|([0-9]{2}0[1-9])|([0-9]{2}1[0-2])|([0-9]{2}1[0-2])|([0-9]{2}1[0-2])')]

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/4224784676.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  not_match1[~not_match1.construction_time.astype(str).str.contains(r'([0-9]{2}0[1-9])|([0-9]{2}0[1-9])|([0-9]{2}0[1-9])|([0-9]{2}1[0-2])|([0-9]{2}1[0-2])|([0-9]{2}1[0-2])')]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
64197,115256,9,0,410000,1090723,68,780998.5558,69.14256,一層，二層，三層，騎樓,四層,...,1,0,5.260818,0.508689,0.384149,0.319658,1.286247,0.798578,0.08395,109-07

In [31]:
# 刪除月份00的資料
data = data.drop(index = {71237})

In [32]:
data

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
0,2,1,0,820504,1011122,19,115937.7118,30.878789,二層,十三層,...,1,1,3.216651,2.360415,6.347960,0.421408,0.259130,0.311712,0.082275,101-11
1,3,1,1,850923,1020204,17,234202.7068,59.350563,二十四層,三十層,...,1,1,8.482000,1.320465,0.893130,0.957701,0.794212,0.069713,0.854684,102-02
2,6,1,0,700820,1031209,33,103878.1534,24.066766,二層,二層,...,1,0,2.242399,3.157690,7.202395,1.384427,1.237124,1.259014,0.942919,103-12
3,7,1,0,690325,1040913,35,110000.4950,73.568000,全,二層,...,1,0,2.096059,3.258152,7.277277,1.657483,1.468159,1.413863,1.211620,104-09
4,8,1,0,690325,1090923,40,99940.9456,80.047632,全,二層,...,1,0,2.094389,3.259394,7.277268,1.665824,1.474884,1.416363,1.219951,109-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233662,367014,28,1,870210,1040729,17,74909.4280,76.092230,全,四層,...,1,0,4.398002,2.514017,8.333632,1.433443,0.262413,0.133083,0.240132,104-07
233663,367015,28,1,870210,1100329,23,209769.5390,69.123790,二層，三層，四層,四層,...,1,0,4.403582,2.505987,8.340752,1.441099,0.271113,0.130807,0.232397,110-03
233664,367016,28,1,870210,1090608,22,210586.0716,68.285930,二層，三層，四層,四層,...,1,0,4.389162,2.499071,8.329609,1.431733,0.273903,0.113285,0.224624,109-06
233665,367017,28,0,780615,1020804,24,114698.0368,36.618050,五層,五層,...,1,0,3.198488,2.308803,7.106325,0.309806,0.361038,0.450016,0.522547,102-08
233666,367018,28,0,860625,1020618,16,106949.2416,18.700540,五層,七層,...,1,0,4.752600,2.260364,8.279950,1.700334,0.524938,0.120486,0.493112,102-06

# Add column yearMonth for format xxx-xx/xx-xx

In [33]:
data.trade_time = data.trade_time.astype(str)

In [34]:
data = data.reset_index(drop = True)

In [35]:
from time import time
time1 = time()
for i in range(len(data)) :
    if len(data.trade_time[i]) == 7:
        data.yearMonth[i] = data.trade_time[i][0:3]+'-'+data.trade_time[i][3:5]
    else :
        data.yearMonth[i] = data.trade_time[i][0:2]+'-'+data.trade_time[i][2:4]
        
print(f"總共花費{time()-time1}")

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/1717697203.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.yearMonth[i] = data.trade_time[i][0:3]+'-'+data.trade_time[i][3:5]
C:\Users\admin\AppData\Local\Temp/ipykernel_58452/1717697203.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.yearMonth[i] = data.trade_time[i][0:2]+'-'+data.trade_time[i][2:4]

總共花費473.5825080871582

In [36]:
data.yearMonth.unique()

array(['101-11', '102-02', '103-12', '104-09', '109-09', '109-11',
       '102-03', '102-05', '101-12', '106-05', '102-12', '104-10',
       '101-10', '101-07', '101-09', '109-07', '102-06', '109-06',
       '109-10', '103-08', '102-09', '103-11', '105-10', '102-08',
       '109-08', '106-02', '108-07', '106-08', '104-04', '108-12',
       '106-09', '104-05', '102-11', '103-10', '108-11', '105-11',
       '106-04', '103-04', '106-07', '103-06', '108-06', '108-08',
       '107-10', '107-11', '104-11', '102-10', '102-07', '105-06',
       '108-10', '105-03', '108-04', '102-04', '108-09', '107-07',
       '108-05', '110-05', '107-05', '103-03', '107-09', '103-01',
       '109-04', '105-01', '107-01', '110-04', '109-05', '104-02',
       '104-08', '104-03', '108-02', '105-12', '103-05', '109-02',
       '105-08', '104-12', '103-07', '102-01', '109-03', '107-04',
       '108-01', '110-03', '110-02', '101-08', '107-02', '107-08',
       '106-10', '109-01', '106-03', '108-03', '106-06', '104-06',
       '106-12', '110-01', '104-07', '105-07', '105-05', '106-11',
       '107-12', '105-09', '103-02', '107-03', '106-01', '105-02',
       '107-06', '104-01', '103-09', '105-04', '109-12', '101-04',
       '101-06', '98-10', '98-11', '101-05', '99-06', '99-05', '99-04',
       '98-12', '99-01', '99-03', '100-07', '99-07', '99-02', '100-10',
       '100-09', '100-11', '100-06', '101-01', '100-08', '100-12',
       '100-01', '100-04', '101-03', '101-02', '99-08', '99-11', '99-09',
       '99-12', '100-02', '99-10', '96-01', '98-06', '98-03', '100-05',
       '97-05', '97-06', '97-12', '100-03', '95-02'], dtype=object)

# Add column age for house age

In [37]:
data.trade_time = data.trade_time.astype(int)

In [38]:
import math

In [39]:
time2 = time()
for i in range(len(data)) :
    data.age[i] = math.floor((data.trade_time[i]-data.construction_time[i])/10000)
print(f"總共花費{time()-time2}")

C:\Users\admin\AppData\Local\Temp/ipykernel_58452/449417316.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.age[i] = math.floor((data.trade_time[i]-data.construction_time[i])/10000)

總共花費164.88727712631226

In [40]:
data.age.unique()

array([19, 16, 33, 35, 40, 18, 17, 30, 20,  1,  2, 38, 31, 22, 26, 25, 23,
       21, 24, 15, 39, 34, 36, 27, 28, 32, 29,  0, 14, 11,  8,  7, 13,  5,
        6, 10,  9, 37, 49,  3,  4, 41, 12, -1, -2, 48, 42, -5, -4, -3, 45,
       44, 47, 56, 54, 43, 46, 50, 52, 51, 53, 59, 55, 57, 58, 63, 67, 62,
       60, 65, 69, 71, -6, 91, 89, 64, 70, 61, 68], dtype=int64)

In [41]:
data[data['age'].isin([0,1,2,-1,-2,-3,-4,-5,-6])]

,id,section,parking_space,construction_time,trade_time,age,unit_price_ping,area,trasaction_floor,total_floor,...,partition,mgmt,min_inci,min_hos,min_mrt,min_mart,min_gas,min_school,min_park,yearMonth
13,17,1,1,1000414,1011012,1,177815.6762,64.280336,十四層,十九層,...,1,1,3.449971,2.309428,6.167956,0.109811,0.290849,0.032921,0.007565,101-10
14,18,1,1,1000414,1010703,1,179967.7520,56.510378,十五層,十九層,...,1,1,3.449971,2.309428,6.167956,0.109811,0.290849,0.032921,0.007565,101-07
15,19,1,1,1000414,1020328,1,200837.2674,64.281188,十七層,十九層,...,1,1,3.449971,2.309428,6.167956,0.109811,0.290849,0.032921,0.007565,102-03
16,20,1,1,1000414,1010721,1,137676.6526,56.509472,五層,十九層,...,1,1,3.449971,2.309428,6.167956,0.109811,0.290849,0.032921,0.007565,101-07
17,22,1,1,1000414,1010721,1,175924.7586,61.447000,十三層,十九層,...,1,1,3.441805,2.313145,6.174962,0.118508,0.287999,0.030001,0.001564,101-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231638,361115,28,1,1041030,1050617,0,50165.5150,35.482700,四層,五層,...,1,0,3.510331,1.414780,7.013821,0.739383,0.109684,0.805026,0.530270,105-06
232241,362867,28,0,1001230,1020315,1,256576.3612,72.103620,全,四層,...,1,1,3.746962,2.622380,7.679056,0.804068,0.227952,0.151608,0.688710,102-03
232242,362869,28,1,1001230,1011126,0,250939.9722,72.527630,全,四層,...,1,0,3.752737,2.609018,7.679691,0.799821,0.241499,0.144059,0.676206,101-11
232401,363048,28,0,1060707,1080420,1,217812.5504,34.433430,二層,四層,...,1,1,2.990713,2.167275,6.869139,0.199889,0.184764,0.418540,0.562239,108-04
232643,363331,28,0,1081225,1100418,1,229164.6676,50.967950,全,三層,...,1,0,4.587341,1.375694,8.803339,3.281222,0.901163,1.471958,1.168530,110-04

In [ ]:
data.to_csv('')